# Site settings
title: Gáy một chút về công nghệ | Bàn luận về Linux, cpp, etc
description: "Gáy một chút về công nghệ."
url: "https://www.tung21.github.io"
author:
  name: "Đỗ Minh Tùng"
  email: "it.endlov3@gmail.com"
  url: "https://www.tung21.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page/:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
